/* ============================================================
   AuditMate — Email route (Brevo / formerly Sendinblue)
   Mounted at: POST /api/email  (protected by authenticateToken in server.js)
   Uses Brevo's REST API directly — no SDK required.
   ============================================================ */
'use strict';

const router = require('express').Router();
const BREVO_ENDPOINT = 'https://api.brevo.com/v3/smtp/email';

function emailReady() {
  const key = process.env.SENDGRID_API_KEY;
  return !!(key && key !== 'your_sendgrid_api_key_here' && key.length > 20);
}

// POST /api/email
router.post('/', async (req, res) => {
  const { to, subject, message, report, jobDetails } = req.body;
  if (!to || !subject) {
    return res.status(400).json({ error: 'to and subject are required' });
  }

  if (!emailReady()) {
    return res.status(503).json({
      error: 'Email not configured — add your Brevo API key as SENDGRID_API_KEY in .env and restart the server.',
      notConfigured: true,
    });
  }

  const fromEmail = process.env.SENDGRID_FROM_EMAIL || 'noreply@auditmate.app';
  const fromName  = process.env.SENDGRID_FROM_NAME  || 'AuditMate';
  const jd = jobDetails || {};

  const htmlContent = buildHtmlEmail({ message, report, jd });
  const textContent = [(message || ''), report ? '---\n\n' + report : ''].filter(Boolean).join('\n\n');

  // Brevo expects `to` as an array of { email, name? } objects
  const toList = [{ email: to }];

  const payload = {
    sender:      { name: fromName, email: fromEmail },
    to:          toList,
    subject,
    htmlContent,
    textContent,
  };

  try {
    const response = await fetch(BREVO_ENDPOINT, {
      method:  'POST',
      headers: {
        'Content-Type': 'application/json',
        'api-key':      process.env.SENDGRID_API_KEY,
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errBody = await response.json().catch(() => ({}));
      const errMsg  = errBody.message || `Brevo API error ${response.status}`;
      console.error('Brevo error:', errBody);
      return res.status(500).json({ error: errMsg });
    }

    res.json({ success: true });
  } catch (err) {
    console.error('Email send error:', err.message);
    res.status(500).json({ error: err.message || 'Failed to send email' });
  }
});

// ── HTML email template ──────────────────────────────────────
function buildHtmlEmail({ message, report, jd }) {
  const reportHtml = report ? mdToHtml(report) : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, Helvetica, sans-serif; color: #1e293b; max-width: 680px; margin: 0 auto; padding: 20px; font-size: 14px; }
  .hdr { background: #1e3a5f; color: #fff; padding: 22px 24px; border-radius: 10px 10px 0 0; }
  .hdr h1 { margin: 0; font-size: 20px; }
  .hdr p  { margin: 6px 0 0; opacity: .85; font-size: 13px; }
  .meta   { background: #f1f5f9; border: 1px solid #e2e8f0; border-top: none; padding: 10px 20px; border-radius: 0 0 6px 6px; margin-bottom: 20px; display: flex; flex-wrap: wrap; gap: 14px; }
  .meta span { font-size: 13px; color: #475569; }
  .msgbox { background: #fffbeb; border: 1px solid #fed7aa; border-radius: 8px; padding: 14px 16px; margin-bottom: 20px; line-height: 1.6; }
  .rpt { border-top: 2px solid #e2e8f0; padding-top: 20px; }
  h2 { color: #1e3a5f; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-top: 20px; }
  h3 { color: #334155; margin-top: 14px; }
  p  { margin: 0 0 10px; }
  ul { margin: 4px 0 10px 20px; }
  li { margin-bottom: 3px; }
  table { width: 100%; border-collapse: collapse; margin: 10px 0 16px; }
  th { background: #1e3a5f; color: white; padding: 8px; text-align: left; font-size: 12px; }
  td { border: 1px solid #e2e8f0; padding: 7px; font-size: 13px; }
  tr:nth-child(even) td { background: #f8fafc; }
  blockquote { border-left: 3px solid #2563eb; margin: 8px 0; padding-left: 12px; color: #475569; }
  .footer { margin-top: 28px; padding-top: 14px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
  <div class="hdr">
    <h1>📋 AuditMate — Site Audit Report</h1>
    ${jd.clientName ? `<p>${esc(jd.clientName)}${jd.siteAddress ? ' · ' + esc(jd.siteAddress) : ''}${jd.date ? ' · ' + esc(jd.date) : ''}</p>` : ''}
  </div>
  <div class="meta">
    ${jd.jobType        ? `<span>🔧 ${esc(jd.jobType)}</span>`           : ''}
    ${jd.electricianName? `<span>👤 ${esc(jd.electricianName)}</span>`   : ''}
    ${jd.licenseNumber  ? `<span>🪪 Lic: ${esc(jd.licenseNumber)}</span>`: ''}
    ${jd.referenceNumber? `<span>📄 Ref: ${esc(jd.referenceNumber)}</span>`:''}
  </div>
  ${message ? `<div class="msgbox">${esc(message).replace(/\n/g, '<br>')}</div>` : ''}
  ${reportHtml ? `<div class="rpt">${reportHtml}</div>` : ''}
  <div class="footer">
    <p>Generated by <strong>AuditMate</strong> · Professional Site Audit Software</p>
    <p>Sent ${new Date().toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' })}</p>
  </div>
</body>
</html>`;
}

// ── Helpers ──────────────────────────────────────────────────
function esc(str) {
  if (!str) return '';
  return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function mdToHtml(md) {
  if (!md) return '';
  let h = md
    .replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
    .replace(/^### (.+)$/gm,'<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm,  '<h1>$1</h1>')
    .replace(/---+/g, '<hr>')
    .replace(/\*\*\*(.+?)\*\*\*/g,'<strong><em>$1</em></strong>')
    .replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>')
    .replace(/\*(.+?)\*/g,'<em>$1</em>')
    .replace(/^&gt; (.+)$/gm,'<blockquote>$1</blockquote>')
    .replace(/^[\*\-] (.+)$/gm,'<li>$1</li>')
    .replace(/(<li>[\s\S]+?<\/li>)/g,'<ul>$1</ul>')
    .replace(/<\/ul>\s*<ul>/g,'')
    .replace(/\|(.+)\|/g, m => '<tr>' + m.split('|').filter(Boolean).map(c=>`<td>${c.trim()}</td>`).join('') + '</tr>')
    .replace(/(<tr>[\s\S]+?<\/tr>)/g,'<table>$1</table>')
    .replace(/<\/table>\s*<table>/g,'')
    .replace(/\n\n+/g,'</p><p>')
    .replace(/\n/g,'<br>');
  if (!h.startsWith('<h') && !h.startsWith('<ul') && !h.startsWith('<table') && !h.startsWith('<hr')) h = '<p>' + h + '</p>';
  return h;
}

module.exports = router;
